#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,metrics,info

spring:
  graphql:
    schema:
      printer:
        enabled: false
      locations: classpath:graphql/
      file-extensions: .graphqls, .gqls
    path: "/graphql"
    graphiql:
      enabled: true
      path: "/graphiql"
books:
  rest_api: "https://www.googleapis.com/books/v1/volumes"
